def test_generate_diet_plan(test_app, auth_headers):
    req_data = {
        "age": 25, "weight": 65, "height": 170, "gender": "female",
        "dietary_preference": "non-vegetarian", "allergies": "",
        "activity_level": "sedentary", "goal": "maintain"
    }
    response = test_app.post("/api/diet/generate", headers=auth_headers, json=req_data)
    assert response.status_code == 201
    data = response.json()
    assert "meals" in data
    assert "total_calories" in data
    
def test_generate_vegetarian_plan(test_app, auth_headers):
    req_data = {
        "age": 25, "weight": 65, "height": 170, "gender": "female",
        "dietary_preference": "vegetarian", "allergies": "",
        "activity_level": "sedentary", "goal": "maintain"
    }
    response = test_app.post("/api/diet/generate", headers=auth_headers, json=req_data)
    assert response.status_code == 201
    data = response.json()
    assert "vegetarian" in data.get("meals", "").lower() or data.get("dietary_preference", "").lower() == "vegetarian"

def test_generate_vegan_plan(test_app, auth_headers):
    req_data = {
        "age": 25, "weight": 65, "height": 170, "gender": "female",
        "dietary_preference": "vegan", "allergies": "dairy",
        "activity_level": "sedentary", "goal": "maintain"
    }
    response = test_app.post("/api/diet/generate", headers=auth_headers, json=req_data)
    assert response.status_code == 201
    data = response.json()
    assert "vegan" in data.get("meals", "").lower() or data.get("dietary_preference", "").lower() == "vegan"

def test_list_plans(test_app, auth_headers):
    # Generate one first
    test_generate_diet_plan(test_app, auth_headers)
    response = test_app.get("/api/diet/plans", headers=auth_headers)
    assert response.status_code == 200
    data = response.json()
    assert isinstance(data, list)
    assert len(data) > 0

def test_get_plan_by_id(test_app, auth_headers):
    req_data = {
        "age": 30, "weight": 80, "height": 180, "gender": "male",
        "dietary_preference": "vegetarian", "allergies": "",
        "activity_level": "moderate", "goal": "muscle gain"
    }
    gen_response = test_app.post("/api/diet/generate", headers=auth_headers, json=req_data)
    plan_id = gen_response.json()["id"]

    response = test_app.get(f"/api/diet/plans/{plan_id}", headers=auth_headers)
    assert response.status_code == 200
    assert response.json()["id"] == plan_id

def test_get_other_users_plan(test_app, auth_headers, test_db):
    # Mocking user isolation: a plan generated by another user
    from backend.models import User, DietPlan
    from backend.auth import create_access_token
    
    other_user = User(email="other@example.com", name="Other", hashed_password="pw")
    test_db.add(other_user)
    test_db.commit()
    test_db.refresh(other_user)
    
    plan = DietPlan(user_id=other_user.id, plan_data={"meals": "test"})
    test_db.add(plan)
    test_db.commit()
    test_db.refresh(plan)
    
    response = test_app.get(f"/api/diet/plans/{plan.id}", headers=auth_headers)
    assert response.status_code == 404

def test_delete_plan(test_app, auth_headers):
    req_data = {
        "age": 25, "weight": 65, "height": 170, "gender": "female",
        "dietary_preference": "vegetarian", "allergies": "",
        "activity_level": "sedentary", "goal": "maintain"
    }
    gen_response = test_app.post("/api/diet/generate", headers=auth_headers, json=req_data)
    plan_id = gen_response.json()["id"]

    response = test_app.delete(f"/api/diet/plans/{plan_id}", headers=auth_headers)
    assert response.status_code == 200

def test_delete_other_users_plan(test_app, auth_headers, test_db):
    from backend.models import User, DietPlan
    other_user = User(email="other2@example.com", name="Other2", hashed_password="pw")
    test_db.add(other_user)
    test_db.commit()
    test_db.refresh(other_user)
    
    plan = DietPlan(user_id=other_user.id, plan_data={"meals": "test"})
    test_db.add(plan)
    test_db.commit()
    test_db.refresh(plan)
    
    response = test_app.delete(f"/api/diet/plans/{plan.id}", headers=auth_headers)
    assert response.status_code == 404
